import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Card } from '@/components/layout';
import { IconButton, Pill } from '@/components/ui';
import { colors, space } from '@/theme';

export default function Approval() { const [decision,setDecision]=useState<string>(); const decide=(value:string)=>{Haptics.notificationAsync(value==='Approved'?Haptics.NotificationFeedbackType.Success:Haptics.NotificationFeedbackType.Warning);setDecision(value)}; return <SafeAreaView style={s.safe}><View style={s.header}><IconButton icon="close" onPress={()=>router.back()}/><Text style={s.heading}>Approval Center</Text><View style={{width:42}}/></View>{decision ? <View style={s.result}><View style={[s.resultIcon,{backgroundColor:decision==='Approved'?colors.profit:colors.loss}]}><Ionicons name={decision==='Approved'?'checkmark':'close'} size={36} color={colors.base}/></View><Text style={s.resultTitle}>Trade {decision.toLowerCase()}</Text><Text style={s.resultCopy}>Your decision was sent to your demo account.</Text><Pressable onPress={()=>router.back()} style={s.done}><Text style={s.doneText}>Back to dashboard</Text></Pressable></View> : <View style={s.content}><Text style={s.eyebrow}>Action required</Text><View style={s.timer}><Ionicons name="time-outline" size={18} color={colors.amber}/><Text style={s.timerText}>24s remaining</Text><View style={s.track}><View style={s.progress}/></View></View><Card style={s.card}><View style={s.cardTop}><Pill label="AI 86" tone="violet"/><Text style={s.provider}>Atlas Signals</Text></View><Text style={s.symbol}>BUY <Text style={{color:colors.cyan}}>XAU/USD</Text></Text><Text style={s.price}>2,365.42</Text><View style={s.levels}><Level label="Entry" value="2,365.42"/><Level label="Stop loss" value="2,354.20" danger/><Level label="Take profit" value="2,389.10" good/></View><View style={s.rationale}><Ionicons name="sparkles" size={17} color={colors.violet}/><Text style={s.rationaleText}>Strong risk-to-reward ratio (1:2.1) with an entry near support. Current market conditions match the provider’s strategy.</Text></View></Card><View style={s.warning}><Ionicons name="shield-checkmark-outline" size={18} color={colors.blue}/><Text style={s.warningText}>Risk check passed: within your daily limit and SL cap.</Text></View><View style={s.actions}><Pressable onPress={()=>decide('Reject')} style={s.reject}><Ionicons name="close" color={colors.loss} size={20}/><Text style={s.rejectText}>Reject</Text></Pressable><Pressable onPress={()=>decide('Approved')} style={s.approve}><Ionicons name="checkmark" color={colors.base} size={20}/><Text style={s.approveText}>Approve trade</Text></Pressable></View><Text style={s.note}>This is a demo trade. You can change this provider’s approval mode in Providers.</Text></View>}</SafeAreaView> }
function Level({label,value,danger,good}:{label:string;value:string;danger?:boolean;good?:boolean}){const color=danger?colors.loss:good?colors.profit:colors.text;return <View><Text style={s.levelLabel}>{label}</Text><Text style={[s.levelValue,{color}]}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.base},header:{padding:space.base,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},heading:{color:colors.text,fontSize:16,fontWeight:'800'},content:{padding:space.base,paddingTop:space.lg},eyebrow:{color:colors.amber,textTransform:'uppercase',letterSpacing:1.2,fontSize:11,fontWeight:'800',marginBottom:10},timer:{backgroundColor:'#FFB80012',borderRadius:12,padding:12,flexDirection:'row',alignItems:'center',gap:8,marginBottom:18},timerText:{color:colors.amber,fontFamily:'monospace',fontWeight:'800',fontSize:14},track:{flex:1,height:4,backgroundColor:colors.hover,borderRadius:2,marginLeft:4,overflow:'hidden'},progress:{width:'62%',height:'100%',backgroundColor:colors.amber},card:{padding:20},cardTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},provider:{color:colors.muted,fontSize:12},symbol:{color:colors.text,fontWeight:'800',fontSize:25,marginTop:24,letterSpacing:-.5},price:{fontFamily:'monospace',fontWeight:'800',fontSize:31,color:colors.text,marginTop:5},levels:{marginTop:22,paddingTop:15,borderTopWidth:1,borderTopColor:colors.card,flexDirection:'row',justifyContent:'space-between'},levelLabel:{color:colors.subtle,textTransform:'uppercase',fontWeight:'800',fontSize:9,letterSpacing:.7},levelValue:{fontFamily:'monospace',fontWeight:'700',fontSize:13,marginTop:5},rationale:{backgroundColor:'#7C5CFF16',borderRadius:12,padding:12,marginTop:22,flexDirection:'row',gap:9},rationaleText:{color:colors.muted,fontSize:12,lineHeight:18,flex:1},warning:{marginTop:16,backgroundColor:'#0B8CFF12',padding:12,borderRadius:12,flexDirection:'row',gap:9,alignItems:'center'},warningText:{color:colors.muted,fontSize:12,flex:1,lineHeight:17},actions:{flexDirection:'row',gap:10,marginTop:22},reject:{height:54,borderRadius:12,borderWidth:1,borderColor:'#FF525250',flex:1,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},rejectText:{color:colors.loss,fontWeight:'800'},approve:{height:54,borderRadius:12,backgroundColor:colors.profit,flex:1.5,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},approveText:{color:colors.base,fontWeight:'800'},note:{color:colors.subtle,textAlign:'center',fontSize:11,lineHeight:16,marginTop:16,paddingHorizontal:16},result:{flex:1,justifyContent:'center',alignItems:'center',padding:32},resultIcon:{width:78,height:78,borderRadius:30,alignItems:'center',justifyContent:'center'},resultTitle:{color:colors.text,fontSize:26,fontWeight:'800',marginTop:24},resultCopy:{color:colors.muted,textAlign:'center',marginTop:8},done:{backgroundColor:colors.cyan,paddingHorizontal:20,paddingVertical:15,borderRadius:12,marginTop:28},doneText:{color:colors.base,fontWeight:'800'}});
