import { Ionicons } from '@expo/vector-icons';
import { Link } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Page, Card } from '@/components/layout';
import { BrandMark, IconButton, Pill, ScreenTitle } from '@/components/ui';
import { trades } from '@/data/demo';
import { colors, space } from '@/theme';

export default function Dashboard() { return <Page><View style={s.top}><BrandMark /><View style={s.topRight}><View style={s.live}><View style={s.dot} /><Text style={s.liveText}>DERIV DEMO</Text></View><IconButton icon="notifications-outline" /></View></View><View style={s.banner}><Ionicons name="shield-checkmark" size={17} color={colors.cyan} /><Text style={s.bannerText}>Your demo account is protected by active risk limits.</Text></View><ScreenTitle eyebrow="Overview" title="Good evening, Alex" action={<IconButton icon="ellipsis-horizontal" />} /><Card style={s.balance}><Text style={s.label}>DERIV DEMO BALANCE</Text><Text style={s.money}>$12,450.80</Text><View style={s.pnlRow}><Ionicons name="trending-up" size={16} color={colors.profit} /><Text style={s.pnl}>+$1,240.50 today</Text><Text style={s.subtle}> +11.06%</Text></View><View style={s.spark}><View style={[s.bar,{height:18}]} /><View style={[s.bar,{height:26}]} /><View style={[s.bar,{height:22}]} /><View style={[s.bar,{height:36}]} /><View style={[s.bar,{height:31}]} /><View style={[s.bar,{height:45}]} /><View style={[s.bar,{height:40}]} /></View></Card><View style={s.stats}><Stat icon="swap-horizontal" value="8 / 10" label="Today’s trades" /><Stat icon="trophy-outline" value="75%" label="Win rate" /><Stat icon="sparkles-outline" value="82" label="AI average" /></View><View style={s.section}><Text style={s.sectionTitle}>Needs your attention</Text><Link href="/approval" asChild><Pressable style={({pressed}) => [s.approval, pressed && { opacity:.8 }]}><View style={s.approvalIcon}><Ionicons name="time-outline" size={20} color={colors.base} /></View><View style={{flex:1}}><Text style={s.approvalTitle}>1 signal awaiting approval</Text><Text style={s.approvalCopy}>Atlas Signals · XAU/USD BUY</Text></View><Ionicons name="chevron-forward" size={20} color={colors.amber} /></Pressable></Link></View><View style={s.section}><View style={s.sectionHeader}><Text style={s.sectionTitle}>Live trade feed</Text><Link href="/feed" style={s.link}>View all</Link></View>{trades.slice(0,2).map(t => <View key={t.id} style={s.trade}><View style={[s.side,{backgroundColor:t.side === 'BUY' ? colors.successSurface : colors.dangerSurface}]}><Text style={{color:t.side === 'BUY' ? colors.profit : colors.loss,fontWeight:'800',fontSize:11}}>{t.side}</Text></View><View style={{flex:1}}><Text style={s.symbol}>{t.symbol}</Text><Text style={s.tradeMeta}>{t.provider} · {t.time}</Text></View><View style={{alignItems:'flex-end'}}><Text style={[s.tradePnl,{color:t.pnl >= 0 ? colors.profit : colors.loss}]}>{t.pnl >= 0 ? '+' : ''}${t.pnl.toFixed(2)}</Text><Pill label={t.status} tone="green" /></View></View>)}</View></Page> }
function Stat({icon,value,label}:{icon:keyof typeof Ionicons.glyphMap;value:string;label:string}) { return <View style={s.stat}><Ionicons name={icon} size={18} color={colors.cyan}/><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View> }
const s=StyleSheet.create({top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:space.lg},topRight:{flexDirection:'row',gap:space.sm,alignItems:'center'},live:{backgroundColor:colors.successSurface,borderRadius:999,paddingHorizontal:8,paddingVertical:6,flexDirection:'row',gap:5,alignItems:'center'},dot:{width:6,height:6,borderRadius:3,backgroundColor:colors.profit},liveText:{color:colors.profit,fontSize:9,fontWeight:'800'},banner:{backgroundColor:'#00D4AA12',borderRadius:12,padding:12,flexDirection:'row',gap:8,alignItems:'center',marginBottom:space.xl},bannerText:{color:colors.muted,fontSize:12,flex:1,lineHeight:18},balance:{padding:20,overflow:'hidden'},label:{color:colors.subtle,fontSize:10,fontWeight:'800',letterSpacing:1},money:{color:colors.text,fontSize:36,fontWeight:'800',letterSpacing:-1.5,marginTop:8},pnlRow:{flexDirection:'row',alignItems:'center',marginTop:8},pnl:{color:colors.profit,fontSize:14,fontWeight:'800'},subtle:{color:colors.subtle,fontSize:12},spark:{height:50,alignItems:'flex-end',gap:7,flexDirection:'row',marginTop:14},bar:{backgroundColor:colors.cyan,width:16,borderRadius:8,opacity:.85},stats:{flexDirection:'row',gap:8,marginTop:12},stat:{flex:1,backgroundColor:colors.elevated,borderRadius:14,borderColor:colors.card,borderWidth:1,padding:12,gap:4},statValue:{color:colors.text,fontSize:17,fontWeight:'800',marginTop:3},statLabel:{color:colors.subtle,fontSize:10,lineHeight:13},section:{marginTop:28},sectionTitle:{color:colors.text,fontSize:18,fontWeight:'800',letterSpacing:-.3},sectionHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12},link:{color:colors.cyan,fontSize:12,fontWeight:'700'},approval:{backgroundColor:'#FFB80014',borderColor:colors.amber,borderWidth:1,borderRadius:16,padding:14,flexDirection:'row',alignItems:'center',gap:12,marginTop:12},approvalIcon:{width:38,height:38,borderRadius:12,backgroundColor:colors.amber,alignItems:'center',justifyContent:'center'},approvalTitle:{color:colors.text,fontSize:14,fontWeight:'800'},approvalCopy:{color:colors.muted,fontSize:12,marginTop:3},trade:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:14,borderBottomWidth:1,borderBottomColor:colors.card},side:{width:42,height:32,borderRadius:10,justifyContent:'center',alignItems:'center'},symbol:{color:colors.text,fontWeight:'800',fontSize:14},tradeMeta:{color:colors.subtle,fontSize:11,marginTop:3},tradePnl:{fontSize:14,fontWeight:'800',marginBottom:5}});
